package test.papers;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.fail;

import org.junit.Before;
import org.junit.Test;

/**
 * This class has been generated by Muggl for the automated testing of method
 * test.papers.Paper200809.binSearch(int v, int[] a).
 * Test cases have been computed using the symbolic execution of Muggl. Muggl
 * is a tool for the fully automated generation of test cases by analysing a
 * program's byte code. It aims at testing any possible flow through the program's
 * code rather than "guessing" required test cases, as a human would do.
 * Refer to http://www.wi.uni-muenster.de/pi/personal/majchrzak.php for more
 * information or contact the author at tim.majchrzak@wi.uni-muenster.de.
 * 
 * Executing the method main(null) will invoke JUnit (if it is in the class path).
 * The methods for setting up the test and for running the tests have also been
 * annotated.
 * 
 * Important settings for this run:
 * Search algorithm:            iterative deepening depth first
 * Time Limit:                  1 minutes
 * Maximum loop cycles to take: 200
 * Maximum instructions before
 * finding a new solution:     10000
 * 
 * The total number of solutions found was 48. After deleting redundancy and
 * removing unnecessary solutions, 48 distinct test cases were found.
 * By eliminating solutions based on their contribution to the
 * def-use chain and control graph edge coverage
 * the total number of solutions could be reduced by 45 to the final number of 3 test cases.
 * 
 * Covered def-use chains:		13 of 13
 * Covered control graph edges:	43 of 48
 * 
 * This file has been generated on Wednesday, 20 August, 2008 5:38 PM.
 * 
 * @author Muggl 1.00 Alpha (unreleased)
 */
public class BinarySearch {
	// Fields for test parameters and expected return values.
	private int int1;
	private int int6;
	private int intm1;
	private int int0;
	private int[] array0 = {5,6,7,8,9};
	private int[] array1 = new int[0];
	private int[] array2 = null;

	/**
	 * Set up the unit test by initializing the fields to the desired values.
	 */
	@Before public void setUp() {
		this.int1 = 1;
		this.int6 = 6;
		this.intm1 = -1;
		this.int0 = 0;
	}

	/**
	 * Run the tests on test.papers.Paper200809.binSearch(int v, int[] a).
	 */
	@Test public void testIt() {
		assertEquals(this.int1, test.papers.Paper200809.binSearch(this.int6, this.array0));
		assertEquals(this.intm1, test.papers.Paper200809.binSearch(this.int0, this.array1));
		try {
			test.papers.Paper200809.binSearch(this.int0, this.array2);
			fail("Expected a java.lang.NullPointerException to be thrown.");
		} catch (java.lang.NullPointerException e) {
			// Do nothing - this is what we expect to happen!
		}
	}

	/**
	 * Invoke JUnit to run the unit tests.
	 * @param args Command line arguments, which are ignored here. Just supply null.
	 */
	public static void main(String args[]) {
		org.junit.runner.JUnitCore.main("test.papers.BinarySearch");
	}

}