package de.wwu.muggl.vm.initialization;

/**
 * Represents an Objectref, but for a Free Object, i.e. one that is used as a logic variable.
 */
public class FreeObjectref extends Objectref {
    /**
     * Private constructor to get concrete instances of an initialized class. These instances
     * have a reference to the InitializedClass, which keeps control of the static
     * fields. The concrete instance itself keeps control of instance fields.
     *
     * @param staticReference  The InitializedClass (which has been generated by the ClassFile).
     * @param primitiveWrapper Toggles the usage of the Objectref as a wrapper for primitive types.
     */
    public FreeObjectref(InitializedClass staticReference, boolean primitiveWrapper) {
        super(staticReference, primitiveWrapper);
    }

    @Override
    public boolean isOfASpecificType() {
        // TODO Make sure that this can become true if the type is sufficiently constrained.
        return false;
    }
}
