language: java
sudo: required
jdk:
  - oraclejdk8

git:
  depth: 3
  
branches:
  only:
  - master
  - javaee
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/.
  
script: 
  - ./gradlew build

after_success:
  - ./gradlew codeCoverageReport
  - bash <(curl -s https://codecov.io/bash)
