package test.papers;

import static org.junit.Assert.assertEquals;

import org.junit.Before;
import org.junit.Test;

/**
 * This class has been generated by Muggl for the automated testing of method
 * test.papers.Paper200809.fibonacci(long x).
 * Test cases have been computed using the symbolic execution of Muggl. Muggl
 * is a tool for the fully automated generation of test cases by analysing a
 * program's byte code. It aims at testing any possible flow through the program's
 * code rather than "guessing" required test cases, as a human would do.
 * Refer to http://www.wi.uni-muenster.de/pi/personal/majchrzak.php for more
 * information or contact the author at tim.majchrzak@wi.uni-muenster.de.
 * 
 * Executing the method main(null) will invoke JUnit (if it is in the class path).
 * The methods for setting up the test and for running the tests have also been
 * annotated.
 * 
 * Important settings for this run:
 * Search algorithm:            iterative deepening depth first
 * Time Limit:                  15 seconds
 * Maximum loop cycles to take: 200
 * Maximum instructions before
 * finding a new solution:     10000
 *
 * Execution has been aborted before it was finished. The time limit has been reached.
 * It might be possible to get more test cases by having less restrictive abortion
 * criteria.
 * 
 * The total number of solutions found was 7. After deleting redundancy and
 * removing unnecessary solutions, 7 distinct test cases were found.
 * By eliminating solutions based on their contribution to the
 * def-use chain and control graph edge coverage
 * the total number of solutions could be reduced by 6 to the final number of 1 test cases.
 * 
 * Covered def-use chains:		0 of 0
 * Covered control graph edges:	23 of 28
 * 
 * This file has been generated on Sunday, 31 August, 2008 12:15 PM.
 * 
 * @author Muggl 1.00 Alpha (unreleased)
 */
public class Fibonacci {
	// Fields for test parameters and expected return values.
	private test.papers.Paper200809 testedClass;
	private long long8;
	private long long6;

	/**
	 * Set up the unit test by initializing the fields to the desired values.
	 */
	@Before public void setUp() {
		this.testedClass = new test.papers.Paper200809();
		this.long8 = 8;
		this.long6 = 6;
	}

	/**
	 * Run the tests on test.papers.Paper200809.fibonacci(long x).
	 */
	@Test public void testIt() {
		assertEquals(this.long8, this.testedClass.fibonacci(this.long6));
	}

	/**
	 * Invoke JUnit to run the unit tests.
	 * @param args Command line arguments, which are ignored here. Just supply null.
	 */
	public static void main(String args[]) {
		org.junit.runner.JUnitCore.main("test.papers.Fibonacci");
	}

}